name: aviato-bot

services:
  aviato-bot:
    build: .
    image: ghcr.io/benjaminhr/aviato:latest
    env_file:
      - .env
    depends_on:
      - vpn
    network_mode: "service:vpn"

  prometheus:
    image: prom/prometheus:v2.52.0
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.enable-lifecycle'

  nodeexporter:
    image: prom/node-exporter:v1.1.2
    ports:
      - "9100:9100"
    restart: unless-stopped

  grafana:
    image: grafana/grafana:8.1.2
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
    ports:
      - "3000:3000"
    restart: unless-stopped

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 900 aviato-bot-aviato-bot-1

volumes:
  prometheus_data:
  grafana_data: