name: aviato-bot

services:
  aviato-bot:
    build: ./app
    image: ghcr.io/benjaminhr/aviato:latest
    ports:
      - "80:8080"
    env_file:
      - .env

  ytdlp-updater:
    build: ./ytdlp-update-job
    environment:
      GITHUB_TOKEN: ${GITHUB_TOKEN}
      GITHUB_REPOSITORY: ${GITHUB_REPOSITORY}
    env_file:
      - .env
    restart: "on-failure"
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
    healthcheck:
      test: ["CMD-SHELL", "curl -fs https://github.com || exit 1"]
      interval: 24h
      timeout: 10s
      retries: 3

  prometheus:
    image: prom/prometheus:v2.52.0
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.enable-lifecycle'

  nodeexporter:
    image: prom/node-exporter:v1.1.2
    ports:
      - "9100:9100"
    restart: unless-stopped

  grafana:
    image: grafana/grafana:8.1.2
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
    ports:
      - "3000:3000"
    restart: unless-stopped

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 500 aviato-bot-aviato-bot-1

volumes:
  prometheus_data:
  grafana_data: